### ISSUE TITLE
Selected diff mode is not properly styled/denoted.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/diff#20]
I'm splitting this from #16

- D7 (notice how the "Standard" diff mode is also denoted as the currently selected one, by making it not look like a link 👍🏼 ):
  <img width=50% src="https://user-images.githubusercontent.com/2423362/135305137-170eeced-2851-418a-95b2-e9d4fbba70fb.png">
- Backdrop (both options are shown as links - can you tell which diff mode is active?? 👎🏼 ):
  <img width=50% src="https://user-images.githubusercontent.com/2423362/135305913-84ae69c1-dec8-4098-94a3-f62b365297f3.png">

There's a `@todo` item in https://github.com/backdrop-contrib/diff/blob/1.x-1.x/diff.pages.inc#L250
```php
  $links = array();
  foreach (diff_available_states('node') as $alternative_state => $label) {
    if ($alternative_state == $state) {
      // @todo: Should we show both or just alternatives?
    }
    $links[$alternative_state] = array(
      'title' => $label,
      'href' => ...,
    );
  }
```

That `@todo` item seems to have been placed there in order to skip adding the currently selected diff mode as a link, but I think that we should still show it, but denote the active vs available diff modes differently. I propose that we make them look like secondary buttons instead.

Rough mockup:
<img width=50% src="https://user-images.githubusercontent.com/2423362/135344573-66fb8bd0-134b-41c7-904c-9122ed517979.png">
...or with smaller buttons:
<img width=50% src="https://user-images.githubusercontent.com/2423362/135344966-34e25f72-3a05-46d1-b91d-7451924394cf.png">

**Comment by klonos** [comment]
We should wait until #17 gets fixed before working on this, but then also make sure that this looks nice in both Seven and Basis.

**Comment by klonos** [comment]
I've filed a PR with some initial work, but we should wait until #17 gets fixed before working further on this. Then also make sure that this looks nice in both Seven and Basis.

**Comment by quicksketch** [comment]
I'm not sure about this change. Maybe it's because it lacks an active state? And two separate buttons of equal weight also look a little strange.

![image](https://github.com/user-attachments/assets/d2e1f186-8c9b-48af-9416-9c6f666015e1)

This page definitely could use some design work, but I'm not sure this is the right solution.

**Comment by quicksketch** [comment]
I've been looking into this and for the life of me I can't figure out what the "Marked Down"  diff mode is supposed to do in the first place.

It looks like at one point Diff included a "rendered" mode, but in the current incarnation, that is not available as an option.

Overall, this may need a bigger set of changes, but for now just removing "Marked Down" may be a completely adequate solution, since it does not seem to have any actual functionality.

**Comment by quicksketch** [comment]
For now I've simply hidden the "Marked Down" mode (https://github.com/backdrop-contrib/diff/commit/f22ee3445447210edf69693e770d456287a28931), which seems to only hide fields and not provide any special functionality.

I'll work on improving this if we have multiple diff modes again in the future.

**Comment by quicksketch** [comment]
Now simply with no diff modes at all:

![image](https://github.com/user-attachments/assets/5b79b1a2-b45f-4ed6-80b5-9d15c48a63e8)
